
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BRACKET H HTML LSPAN start : list  list : LSPAN phtml H phtml : HTML phtml : HTML phtml phtml : BRACKET phtml '
    
_lr_action_items = {'LSPAN':([0,],[3,]),'$end':([1,2,7,],[0,-1,-2,]),'HTML':([3,5,6,],[5,5,5,]),'BRACKET':([3,5,6,],[6,6,6,]),'H':([4,5,8,9,],[7,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'list':([0,],[2,]),'phtml':([3,5,6,],[4,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> list','start',1,'p_start','data_extractor_responses.py',63),
  ('list -> LSPAN phtml H','list',3,'p_list','data_extractor_responses.py',66),
  ('phtml -> HTML','phtml',1,'p_HTML','data_extractor_responses.py',116),
  ('phtml -> HTML phtml','phtml',2,'p_HTML_multi','data_extractor_responses.py',121),
  ('phtml -> BRACKET phtml','phtml',2,'p_HTML_2','data_extractor_responses.py',125),
]
